version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - 3000:80
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - 9080:9080
    restart: always
