version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - 3000:80
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - 9080:9080
    restart: always
    depends_on:
      backend-db:
        condition: service_healthy

  backend-db:
    image: postgres:alpine
    user: postgres
    environment:
      POSTGRES_PASSWORD: pass
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
