name: Frontend CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    defaults:
      run:
        working-directory: ./frontend/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./frontend/package-lock.json"
    - run: npm ci
    - run: npx eslint --no-error-on-unmatched-pattern ./src/

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    defaults:
      run:
        working-directory: ./frontend/

    env:
      # so the warnings of the serialization library import *as an expression*
      # do not fail the job, since for the browser env it is fine.
      CI: false

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "./frontend/package-lock.json"
    - run: npm ci
    - run: npm run build
